// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: configs_patch.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const updateConfigCAS = `-- name: UpdateConfigCAS :one
UPDATE configs
SET
  title = COALESCE($3, title),
  is_public = COALESCE($4, is_public),
  colors = COALESCE($5, colors),
  revision = revision + 1,
  updated_at = NOW()
WHERE id = $1 AND revision = $2
RETURNING id, model_id, title, colors, revision, is_public, created_at, updated_at
`

type UpdateConfigCASParams struct {
	ID       pgtype.UUID `json:"id"`
	Revision int64       `json:"revision"`
	Title    pgtype.Text `json:"title"`
	IsPublic pgtype.Bool `json:"is_public"`
	Colors   []byte      `json:"colors"`
}

func (q *Queries) UpdateConfigCAS(ctx context.Context, arg UpdateConfigCASParams) (Config, error) {
	row := q.db.QueryRow(ctx, updateConfigCAS,
		arg.ID,
		arg.Revision,
		arg.Title,
		arg.IsPublic,
		arg.Colors,
	)
	var i Config
	err := row.Scan(
		&i.ID,
		&i.ModelID,
		&i.Title,
		&i.Colors,
		&i.Revision,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
