// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: configs.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createConfig = `-- name: CreateConfig :one
INSERT INTO configs (model_id, title, colors, is_public)
VALUES ($1, $2, $3::jsonb, $4)
RETURNING id, model_id, title, colors, revision, is_public, created_at, updated_at
`

type CreateConfigParams struct {
	ModelID  string      `json:"model_id"`
	Title    pgtype.Text `json:"title"`
	Column3  []byte      `json:"column_3"`
	IsPublic bool        `json:"is_public"`
}

func (q *Queries) CreateConfig(ctx context.Context, arg CreateConfigParams) (Config, error) {
	row := q.db.QueryRow(ctx, createConfig,
		arg.ModelID,
		arg.Title,
		arg.Column3,
		arg.IsPublic,
	)
	var i Config
	err := row.Scan(
		&i.ID,
		&i.ModelID,
		&i.Title,
		&i.Colors,
		&i.Revision,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConfigByID = `-- name: GetConfigByID :one
SELECT id, model_id, title, colors, revision, is_public, created_at, updated_at
FROM configs
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetConfigByID(ctx context.Context, id pgtype.UUID) (Config, error) {
	row := q.db.QueryRow(ctx, getConfigByID, id)
	var i Config
	err := row.Scan(
		&i.ID,
		&i.ModelID,
		&i.Title,
		&i.Colors,
		&i.Revision,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublishedModelExists = `-- name: GetPublishedModelExists :one
SELECT 1
FROM models
WHERE id = $1 AND status = 'published'
LIMIT 1
`

func (q *Queries) GetPublishedModelExists(ctx context.Context, id string) (int32, error) {
	row := q.db.QueryRow(ctx, getPublishedModelExists, id)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
