// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: models.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listModels = `-- name: ListModels :many
SELECT
  id,
  display_name,
  thumbnail_url,
  status,
  updated_at
FROM models
WHERE status != 'archived'
ORDER BY updated_at DESC
`

type ListModelsRow struct {
	ID           string             `json:"id"`
	DisplayName  string             `json:"display_name"`
	ThumbnailUrl pgtype.Text        `json:"thumbnail_url"`
	Status       string             `json:"status"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListModels(ctx context.Context) ([]ListModelsRow, error) {
	rows, err := q.db.Query(ctx, listModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListModelsRow
	for rows.Next() {
		var i ListModelsRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.ThumbnailUrl,
			&i.Status,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
