// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: model_detail.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getModelByID = `-- name: GetModelByID :one
SELECT
  id,
  display_name,
  status,
  gltf_url,
  base_url,
  thumbnail_url,
  updated_at
FROM models
WHERE id = $1
LIMIT 1
`

type GetModelByIDRow struct {
	ID           string             `json:"id"`
	DisplayName  string             `json:"display_name"`
	Status       string             `json:"status"`
	GltfUrl      string             `json:"gltf_url"`
	BaseUrl      pgtype.Text        `json:"base_url"`
	ThumbnailUrl pgtype.Text        `json:"thumbnail_url"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetModelByID(ctx context.Context, id string) (GetModelByIDRow, error) {
	row := q.db.QueryRow(ctx, getModelByID, id)
	var i GetModelByIDRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Status,
		&i.GltfUrl,
		&i.BaseUrl,
		&i.ThumbnailUrl,
		&i.UpdatedAt,
	)
	return i, err
}

const listModelAliases = `-- name: ListModelAliases :many
SELECT
  alias,
  part_id
FROM model_aliases
WHERE model_id = $1
ORDER BY alias ASC
`

type ListModelAliasesRow struct {
	Alias  string `json:"alias"`
	PartID string `json:"part_id"`
}

func (q *Queries) ListModelAliases(ctx context.Context, modelID string) ([]ListModelAliasesRow, error) {
	rows, err := q.db.Query(ctx, listModelAliases, modelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListModelAliasesRow
	for rows.Next() {
		var i ListModelAliasesRow
		if err := rows.Scan(&i.Alias, &i.PartID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModelParts = `-- name: ListModelParts :many
SELECT
  part_id,
  display_name,
  selectable,
  sort_order,
  default_color,
  mesh_selectors
FROM model_parts
WHERE model_id = $1
ORDER BY sort_order ASC, part_id ASC
`

type ListModelPartsRow struct {
	PartID        string      `json:"part_id"`
	DisplayName   string      `json:"display_name"`
	Selectable    bool        `json:"selectable"`
	SortOrder     int32       `json:"sort_order"`
	DefaultColor  pgtype.Text `json:"default_color"`
	MeshSelectors []byte      `json:"mesh_selectors"`
}

func (q *Queries) ListModelParts(ctx context.Context, modelID string) ([]ListModelPartsRow, error) {
	rows, err := q.db.Query(ctx, listModelParts, modelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListModelPartsRow
	for rows.Next() {
		var i ListModelPartsRow
		if err := rows.Scan(
			&i.PartID,
			&i.DisplayName,
			&i.Selectable,
			&i.SortOrder,
			&i.DefaultColor,
			&i.MeshSelectors,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
