// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Config struct {
	ID        pgtype.UUID        `json:"id"`
	ModelID   string             `json:"model_id"`
	Title     pgtype.Text        `json:"title"`
	Colors    []byte             `json:"colors"`
	Revision  int64              `json:"revision"`
	IsPublic  bool               `json:"is_public"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Model struct {
	ID           string             `json:"id"`
	DisplayName  string             `json:"display_name"`
	Status       string             `json:"status"`
	GltfUrl      string             `json:"gltf_url"`
	BaseUrl      pgtype.Text        `json:"base_url"`
	ThumbnailUrl pgtype.Text        `json:"thumbnail_url"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type ModelAlias struct {
	ModelID string `json:"model_id"`
	Alias   string `json:"alias"`
	PartID  string `json:"part_id"`
}

type ModelPart struct {
	ModelID       string      `json:"model_id"`
	PartID        string      `json:"part_id"`
	DisplayName   string      `json:"display_name"`
	Selectable    bool        `json:"selectable"`
	SortOrder     int32       `json:"sort_order"`
	DefaultColor  pgtype.Text `json:"default_color"`
	MeshSelectors []byte      `json:"mesh_selectors"`
}
