export const MODEL_PARTS = {
  shoe: ["laces", "mesh", "caps", "inner", "sole", "stripes", "band", "patch"],
  rocket: ["hull", "base", "top", "wings", "window"],
  axe: ["design", "inner", "support", "body"],
  insect: ["shell", "body"],
  teapot: ["lid", "base"],
};

export const MODEL_ALIASES = {
  shoe: {
    body: "mesh",
    bottom: "sole",
    outsole: "sole",
    inside: "inner",
    interior: "inner",
    "inner lining": "inner",
    logo: "stripes",
    logos: "stripes",
    band: "band",
    bands: "stripes",
    lace: "laces",
    shoelace: "laces",
    shoelaces: "laces",
  },
  rocket: {
    body: "hull",
    tip: "top",
    nose: "top",
    top: "top",
    fins: "wings",
    fin: "wings",
    wing: "wings",
    engine: "base",
    engines: "base",
    tail: "base",
  },
  axe: {
    handle: "body",
    head: "design",
    blade: "design",
    metal: "design",
    grip: "support",
  },
  insect: {
    abdomen: "body",
    carapace: "shell",
  },
  teapot: {
    pot: "base",
    body: "base",
    spout: "base",
    handle: "base",
    top: "lid",
  },
};
